# Generated by Django 3.2.9 on 2022-05-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20220509_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='password1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
