# Generated by Django 3.2.9 on 2022-05-10 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20220510_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='password1',
            new_name='password',
        ),
    ]
